version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
  web:
    build: .
    command: bash -c "./wait-for.sh db:5432 --timeout=60 -- gunicorn chat_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
