version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 chat_project.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
